name: Deploy

on:
  push:
    # branches:
    #   - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - run: echo ${{github.ref}}
      # - run: cat ~/.netrc
      # - name: login
        # run: echo '::set-env name=API_VERSION::${{ github.ref }}'
        # env:
        #   HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        # run: heroku auth:login
      - name: Get auth token 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku config:get VERSION -a "$HEROKU_APP_NAME"

      # - name: Update API_VERSION on Heroku
        # run: heroku config:set API_VERSION=${VERSION##*/} -a ${{ secrets.HEROKU_APP_NAME }}

        # run: |
        #   cat > ~/.netrc <<EOF
        #     machine api.heroku.com
        #       login $HEROKU_EMAIL
        #       password $HEROKU_API_KEY
        #     machine git.heroku.com
        #       login $HEROKU_EMAIL
        #       password $HEROKU_API_KEY
        #   EOF
        #   echo heroku config:get VERSION

      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      #     # HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      #   run: heroku auth:login
      # - name: Get config version
      #   run: heroku config:get VERSION --app=test-bump-version web 

        # sed -i 's/1.0.0/1.0.'$GITHUB_RUN_NUMBER'/' package.json
        # cat package.json
      # - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "test-bump-version" #Must be unique in Heroku
      #     heroku_email: ${{secrets.EMAIL}}
      #     branch: "staging"
          # justlogin: true
      # - run: heroku auth:login
      # - run: heroku auth:whoami
 



    