name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump app version
        run: | 
          heroku config:set REACT_APP_VERSION=0.9.$(git rev-list --count HEAD) -a test-bump-version
          git tag 0.9.$(git rev-list --count HEAD)
          git push -f --tags
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Deploy
 


    