name: Push staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve branch
        run: | 
          echo ${{ github.ref =='refs/heads/staging' && 'staging || main }}
          echo ${{ env }}
          echo  ${{ github.ref ==  }}
      # - name: Push staging
      #   if: ${{github.ref == 'refs/heads/staging'}}
      #   run: echo ${{ 'staging' }}
      # - name: Push main
      #   if: ${{github.ref == 'refs/heads/main'}}
      #   run: echo ${{ 'main' }} 
 
      # - name: Check out repository
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - name: Bump app version
      #   run: | 
      #     declare -r APP_VERSION=0.9.$(git rev-list --count HEAD)
      #     heroku config:set REACT_APP_VERSION=$APP_VERSION -a test-bump-version
      #     git tag $APP_VERSION
      #     git push -f --tags
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 


    